# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Nick Hunkins"
description: "Nick Hunkins' personal website - Powered by Jekyll and GitHub Pages"
author:      "Nick Hunkins, Jekyll theme by Paul Le"
