#-------------------------------
# General Site Settings

menu:
- {name: 'Home', url: ''}
- {name: 'Blog',     url: 'blog'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'PRISM',   url: 'prism'}
- {name: 'Optimizing Hadoop Ingests',   url: 'optimizing-hadoop-ingests'}
- {name: 'ChatGPT Knowledge Probing: Let Alone',   url: 'let-alone-chatgpt'}
- {name: 'Digital Signal Processing: Neurokit 2 EDA',   url: 'eda-signal-processing'}
- {name: 'SMC: Analysis',   url: 'smc-analysis'}
- {name: 'SMC: Annotations', url: 'smc-annotations'}
- {name: 'CETD: Automated Feedback',  url: 'cetd-auto-feedback'}
- {name: 'CETD: Messages of Belonging',  url: 'cetd-belonging'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://instagram.com/nick.hunkins'}
- {icon: 'github',    link: 'https://github.com/nchp89'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/nick-hunkins'}
- {icon: 'envelope',  link: 'mailto:nickhunkins@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
